module.exports = {
	likes: '{likes, number} me gusta.',
	'logout': 'Salir',
	'english': 'Inglés',
	'spanish': 'Español',
	'signup.subheading': 'Regitrate para ver fotos de tus Amig@s Casineros',
	'signup.facebook': 'Inicia sesión con Facebook',
	'signup.text': 'Inicia sesión',
	'email': 'Correo Electrónico',
	'fullname': 'Nombre Completo',
	'username': 'Nombre de Usuario',
	'password': 'Contraseña',
	'signup.call-to-action': 'Registrate',
	'signup.have-account': '¿Tienes una cuenta?',
	'signin': 'Entrar',
	'signin.no-have-account': '¿No tienes una cuenta?',
	'language': 'Idioma',
	'upload-picture': 'Subir foto',
	'upload': 'Subir',
	'cancel': 'Cancelar'
}